name: Build and Release JAR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name to release (e.g., v1.0.0)"
        required: false
      create_release:
        description: "Create GitHub release"
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/zgw-token-introspection.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine tag
        id: vars
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="${{ inputs.tag }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "release_name=zgw-token-introspection $TAG" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: dist

      - name: Create GitHub Release
        if: ${{ steps.vars.outputs.tag != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.vars.outputs.tag }}"
          title="${{ steps.vars.outputs.release_name }}"

          if gh release view "$tag" >/dev/null 2>&1; then
            gh release upload "$tag" "dist/zgw-token-introspection.jar" --clobber
          else
            gh release create "$tag" "dist/zgw-token-introspection.jar" \
              --title "$title" \
              --notes "Automated release $tag" \
              --target "$GITHUB_SHA"
          fi


